### PR TITLE
619-Migrate signature:create command

### LINKED ISSUE #619: Add signature:create command
### Description

Currently commander doesn't have a way to signature for multi-signature transaction.
`signature:create` should create the signature object for broadcasting

### Versions

v2.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by mitsujutsu**
### What was the problem?

Commander 2.0 doesn't have a way to signature for multi-signature transaction.

### How did I fix it?

Create `signature:create` command

### How to test it?

Build, lint, test.

### Review checklist

* The PR resolves #619
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: src/commands/signature/create.js [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+	passphrase: flagParser.string(commonFlags.passphrase),
+};
+
+CreateCommand.description = `
+Create a signature object for a transaction from a multisignature account.
+Accepts a stringified JSON transaction as an argument.
+`;
+
+CreateCommand.examples = [
+	'signature:create \'{"type":0,"amount":"10","recipientId":"100L","senderPublicKey":"abcd1234","timestamp":59353522,"asset":{},"id":"abcd1234","signature":"abcd1234"}\'',
```
Comment (shuse2) [inline src/commands/signature/create.js]: Prefer executable example

File: test/commands/signature/create.test.js [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+
+	const printMethodStub = sandbox.stub();
+	const setupTest = () =>
+		test
+			.stub(print, 'default', sandbox.stub().returns(printMethodStub))
+			.stub(config, 'getConfig', sandbox.stub().returns({}))
+			.stub(
+				elements.default.transaction,
+				'createSignatureObject',
+				transactionStub,
```
Comment (shuse2) [inline test/commands/signature/create.test.js]: why not put the `sandbox.stub().returns(defaultSignatureObject)` as return value here?

**Comment by shuse2** [comment]
One thing I forgot to mention, we we add a new feature, let's update the README at the same time.
readme can be generated using `npx oclif-dev readme --multi` and 
- delete the reference to code (since it reference to dist)
- Fix the link on the top of the page
